### ISSUE TITLE
MacVim hangs if erlang_check found no errors

### ISSUE THREAD

**Issue by sumerman** [jimenezrick/vimerl#10] opened 2011-10-16 04:23 UTC
Actually I am not familar with vimsrcipt, but seems that moving lines

```
setlocal shellpipe&
setlocal makeprg=make
```

from end of the `s:ShowErrors function` to the point just after the `silent make!` resolves the problem.
Maybe it's because `getqflist()` waiting for make's output in any case. But I'm not sure if the suggested solution is safe in a case of long make's output.

**Comment by jimenezrick** [comment] 2011-10-16 19:42
I tried with MacVim and with Vim on Linux and I can't reproduce the issue. Let me ask:
- Does it happen always?
- Could you give me some steps to reproduce it?
- If you are a Linux user, does it happen to you on Linux too?
- Does it happen after enabling/disabling the syntax check with `:ErlangEnableShowErrors` and `:ErlangDisableShowErrors`?
-  Were you working on several Vim buffers with Erlang files?

About moving those two lines of code, I can't see how it does affect to that. `getqflist()` returns an empty list if there is no output from the Make program, so it should work when there are no errors.

**Comment by jimenezrick** [comment] 2011-10-22 16:16
I can't help if I don't have more info, so I am gonna close the issue, reopen it if you find how to reproduce it.

**Closed as completed by jimenezrick** 2011-10-22 16:16 UTC
